### ISSUE TITLE
Wrong order of mac and data for Aead.Xchacha20poly1305Ietf.decrypt()

### ISSUE THREAD

**Issue by tuupola** [ArteMisc/libsalty#2]
Currently calls to `Salty.Aead.Xchacha20poly1305Ietf.decrypt()` always fail. Calls to `Salty.Aead.Xchacha20poly1305Ietf.decrypt_detached()` work as expected. This is probably caused by the following code in [lib/salty/aead.ex](https://github.com/ArteMisc/libsalty/blob/master/lib/salty/aead.ex#L7-L12) which extracts the tag (mac) and data in a wrong order. IIRC in combined mode mac comes after the payload.

```elixir
      def decrypt(nsec, cipher, ad, npub, key) do
        mac_size = abytes()
        <<mac::binary-size(mac_size),
          data::binary>> = cipher
        decrypt_detached(nsec, data, mac, ad, npub, key)
      end
```

**Comment by ArteMisc** [comment]
You are correct, the libsodium source files indicate that the location of the MAC is after the data.
Should be fixed now, thanks!
