### ISSUE TITLE
Hex documentation missing

### ISSUE THREAD

**Issue by thePhilGuy** [ArteMisc/libsalty#3]
Tried to check out your documentation from the hex page, https://hexdocs.pm/libsalty/README.md.html told me to open an issue here if there was a problem with documentation.
It looks it's missing entirely, at least on hex.

**Comment by fhunleth** [comment]
Merging #6 and making a new release to hex should fix this issue.

**Comment by ArteMisc** [comment]
#6 is merged, will make a new release soon

**Comment by daveed-al** [comment]
@ArteMisc libsalty does not compile with current version 0.1.1 on macOS High Sierra pointing to hex.pm.
When I updated it from the master branch (github) it works.

could you please push 0.1.2?

**Comment by ArteMisc** [comment]
0.1.2 is pushed, docs are now available on hex
