### ISSUE TITLE
Salty.Sign.Ed25519.seed_keypair/1 and Salty.Sign.Ed25519.keypair/0 do not return a key pair

### ISSUE THREAD

**Issue by sgessa** [ArteMisc/libsalty#9]
Hi!

I just noticed seed_keypair/1 and keypair/0 only return the secret key so I have to call sk_to_pk/1 manually.
I was expecting them to return a tuple with the secret and public key, am I wrong?

Thank you!

**Comment by ArteMisc** [comment]
This does indeed seem to be a mistake.

https://github.com/ArteMisc/libsalty/blob/master/lib/salty/sign.ex#L54 defines that the returned tuple should be `{:ok, binary(), binary()}`, which matches the api in the original C library. I will update the nif code to fix this.

Thanks for the catch!
